<html lang='pt_BR'>
	<head>
		<title>Ped&gt;histórico de exercícios</title>
		<meta charset="utf-8">
		<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
		<style>BODY { font-family:Raleway; } H1 { color:#75507b; }</style>
	</head>
	<body>
		<div class='container-fluid'>
			<h1><span class="glyphicon glyphicon-stats"></span> Histórico de exercícios</h1>
			<table class="table table-striped">
				<tbody>
					<tr><td>Exercícios</td><td>%_WORKOUTS_%</td></tr>
					<tr><td>Maior distância</td><td>%_FARTHEST_% km</td></tr>
					<tr><td>Distância total</td><td>%_RUNDISTANCE_% km</td></tr>
					<tr><td>Tempo total</td><td>%_TOTALHOU_%h %_TOTALMIN_%m %_TOTALSEC_%s</td></tr>
					<tr><td>Calorias</td><td>%_CALORIES_%</td></tr>
					<tr><td>Número de passos</td><td>%_TOTALSTEPS_%</td></tr>
					<tr><td>&nbsp;&nbsp;Caminhando</td><td>%_WALKING_%</td></tr>
					<tr><td>&nbsp;&nbsp;Correndo</td><td>%_RUNNING_%</td></tr>
					<tr><td>&nbsp;&nbsp;Passada</td><td>&tilde;%_MYSTEPS_% m</td></tr>
				</tbody>
			</table>
			<small>Criado automaticamente pelo 'ped'</small>
		</div>
	</body>
</html>
